#!python
# build should be added into everyone's root level repository. build will:
# * download and set up a virtualenv
# * install uranium

VENV_URL = "https://pypi.python.org/packages/source/v/virtualenv/virtualenv-{major}.{minor}.{rev}.tar.gz"
VENV_MAJOR = 1
VENV_MINOR = 11
VENV_REV = 6

import io
import logging
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile

try:
    import urllib2.urlopen as urlopen
except:
    import urllib.request.urlopen as urlopen

LOGGER = logging.getLogger(__name__)


def main(argv):
    _install_virtualenv()


def _install_virtualenv():
    temp_dir = tempfile.mkdtemp()
    current_dir = os.path.expand(os.curdir)
    try:
        _download_virtualenv(temp_dir)
        virtualenv_dir = os.path.join(temp_dir, "virtualenv-{major}.{minor}.{rev}".format(
            major=VENV_MAJOR, minor=VENV_MINOR, rev=VENV_REV
        ))
        virtualenv_executable = os.path.join(virtualenv_dir, 'virtualenv.py')
        subprocess.call([sys.executable, virtualenv_executable,
                         '--no-site-packages', current_dir])
    finally:
        shutil.rmtree(temp_dir)


def _download_virtualenv(target_dir=None):
    target_dir = target_dir or os.path.abspath(os.curdir)
    venv_url = VENV_URL.format(
        major=VENV_MAJOR, minor=VENV_MINOR, rev=VENV_REV
    )
    _extract_tar(venv_url, target_dir)


def _extract_tar(url, target_dir):
    """ Return a bytesio object with a download bar """
    LOGGER.info("Downloading url: {0}".format(url))
    fileobj = urlopen(url)
    tf = tarfile.TarFile.open(fileobj=fileobj)
    LOGGER.info("extracting to {0}...".format(target_dir))
    tf.extractall(target_dir)


def _create_stdout_logger():
    """ create a logger to stdout """
    log = logging.getLogger(__name__)
    out_hdlr = logging.StreamHandler(sys.stdout)
    out_hdlr.setFormatter(logging.Formatter('%(message)s'))
    out_hdlr.setLevel(logging.INFO)
    log.addHandler(out_hdlr)
    log.setLevel(logging.INFO)

if __name__ == "main":
    _create_stdout_logger()
    main(sys.argv)
